# Generated by Django 2.0.5 on 2019-03-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Number', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=60)),
                ('Product_Cost', models.IntegerField()),
                ('Product_Color', models.CharField(max_length=50)),
                ('Product_Class', models.CharField(max_length=50)),
                ('Number_Of_Products', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Customer_Number', models.IntegerField()),
                ('Email_Id', models.EmailField(max_length=80)),
            ],
        ),
    ]
