# Generated by Django 2.0.5 on 2019-03-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curd_App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Customer_Number',
            field=models.BigIntegerField(),
        ),
    ]
