# Generated by Django 2.0.5 on 2019-03-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curd_App1', '0002_auto_20190322_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_Number',
            new_name='Product_Number',
        ),
    ]
